// <auto-generated />
using System;
using HarvestHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HarvestHub.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HarvestHub.Models.Contador", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("CRC")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("FuncionarioId");

                    b.ToTable("Contador");
                });

            modelBuilder.Entity("HarvestHub.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("HarvestHub.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("HarvestHub.Models.GerenteDeProducao", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("CREA")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("FuncionarioId");

                    b.ToTable("GerenteDeProducao");
                });

            modelBuilder.Entity("HarvestHub.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GerenteDeProducaoCrea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GerenteDeProducaoFuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("Id");

                    b.HasIndex("GerenteDeProducaoFuncionarioId");

                    b.ToTable("Insumo");
                });

            modelBuilder.Entity("HarvestHub.Models.Patrimonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("date");

                    b.Property<string>("GerenteDeProducaoCrea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GerenteDeProducaoFuncionarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("GerenteDeProducaoFuncionarioId");

                    b.ToTable("Patrimonio");
                });

            modelBuilder.Entity("HarvestHub.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContadorFuncionarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ContadorFuncionarioId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("HarvestHub.Models.RecursosHumanos", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("CRA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FuncionarioId");

                    b.ToTable("RecursosHumanos");
                });

            modelBuilder.Entity("HarvestHub.Models.Contador", b =>
                {
                    b.HasOne("HarvestHub.Models.Funcionario", "Funcionario")
                        .WithOne("Contador")
                        .HasForeignKey("HarvestHub.Models.Contador", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("HarvestHub.Models.Contrato", b =>
                {
                    b.HasOne("HarvestHub.Models.Funcionario", "Funcionario")
                        .WithMany("Contratos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("HarvestHub.Models.GerenteDeProducao", b =>
                {
                    b.HasOne("HarvestHub.Models.Funcionario", "Funcionario")
                        .WithOne("GerenteDeProducao")
                        .HasForeignKey("HarvestHub.Models.GerenteDeProducao", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("HarvestHub.Models.Insumo", b =>
                {
                    b.HasOne("HarvestHub.Models.GerenteDeProducao", "GerenteDeProducao")
                        .WithMany("Insumos")
                        .HasForeignKey("GerenteDeProducaoFuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GerenteDeProducao");
                });

            modelBuilder.Entity("HarvestHub.Models.Patrimonio", b =>
                {
                    b.HasOne("HarvestHub.Models.GerenteDeProducao", "GerenteDeProducao")
                        .WithMany("Patrimonios")
                        .HasForeignKey("GerenteDeProducaoFuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GerenteDeProducao");
                });

            modelBuilder.Entity("HarvestHub.Models.Receita", b =>
                {
                    b.HasOne("HarvestHub.Models.Contador", "Contador")
                        .WithMany("Receitas")
                        .HasForeignKey("ContadorFuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contador");
                });

            modelBuilder.Entity("HarvestHub.Models.RecursosHumanos", b =>
                {
                    b.HasOne("HarvestHub.Models.Funcionario", "Funcionario")
                        .WithOne("RecursosHumanos")
                        .HasForeignKey("HarvestHub.Models.RecursosHumanos", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("HarvestHub.Models.Contador", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("HarvestHub.Models.Funcionario", b =>
                {
                    b.Navigation("Contador");

                    b.Navigation("Contratos");

                    b.Navigation("GerenteDeProducao");

                    b.Navigation("RecursosHumanos");
                });

            modelBuilder.Entity("HarvestHub.Models.GerenteDeProducao", b =>
                {
                    b.Navigation("Insumos");

                    b.Navigation("Patrimonios");
                });
#pragma warning restore 612, 618
        }
    }
}
